// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get-sent-messages": {
            "get": {
                "description": "Getting all messages that are sent",
                "tags": [
                    "Service"
                ],
                "summary": "Getting all messages that are sent",
                "responses": {
                    "200": {
                        "description": "Messages ",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/startstop": {
            "get": {
                "description": "Starts or stops the message sending service that sends messages every 2 minutes by sending the action in query",
                "tags": [
                    "Service"
                ],
                "summary": "Starts and stops the message service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action to perform: 'start' or 'stop'",
                        "name": "action",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Service started",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Message Service API",
	Description:      "This is a sample server for the message service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
