services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port
    networks:
      - app-network
  messagingapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: messagingapp
    ports:
      - "8080:8080"
    depends_on:
      - redis  
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=messages.db
      - WEBHOOK_URL=https://webhook.site/ba6a41ba-a547-425f-ad7c-a833f8837b12
      - MESSAGING_PERIOD=120
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
