services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port
    networks:
      - app-network

  insiderapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: insiderapp
    ports:
      - "8080:8080"
    depends_on:
      - redis  
    environment:
      - REDIS_ADDR=redis:6379  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
